# comment
# possible themes on https://pages.github.com/themes/ (use github themes)
#theme: architect

#use of other themes: 
remote_theme: just-the-docs/just-the-docs

#https://github.com/just-the-docs/just-the-docs

